### PR TITLE
Remove patient from cohort

### LINKED ISSUE #66: Pouvoir exclure un patient d'une cohorte existante
## Proposition

Ajouter une colonne "Actions" dans la vue listing de patients (seulement dans le cas d'une cohorte, pas dans le cas d'une exploration de périmètre). Je propose d'utiliser le même bouton-icon "delete" que dans le listing des cohortes de la page d'accueil par exemple.

image

Au hover, mettre un petit tooltip qui dit "Exclure ce patient de la cohorte".

Au clic, mettre un petit loader le temps que l'action s'exécute.

image

Quand c'est fini, le patient ne fait plus partie de la cohorte et on ne le verra plus dans la liste.
Normalement on voit le count de patients de la cohorte s'updater (-1 si tout va bien 😄 )

### PR DESCRIPTION
**Pull request by BPierrick**
## Fixes

Fixes #66 by @MiskoG 

## Description

While exploring a cohort (only for this type of exploration), a column "Action" has been added in patients list to exclude patients from this cohort.

The row has an "exclude loading state" and sets a spinner when refetching the updated cohort.

## Technical details

- The group is updated with an HTTP "put" request because "patch" methods raises HTTP error 400 for unknown reason

## Screenshots

Capture d’écran 2021-04-07 à 11 51 24

### CODE REVIEW

**Comment by MiskoG** [comment]
Nice ! @BPierrick Can we get a little screenshot just in order to check the UI ? 😊

**Review by Jasopaum — COMMENTED** [review]
For the `PATCH`, maybe you need to change the header: https://www.hl7.org/fhir/http.html#patch?

**Comment by BPierrick** [comment]
> Nice ! @BPierrick Can we get a little screenshot just in order to check the UI ? 😊

Done! I'm affraid i'm not fast enough to capture a screenshot while having the loader in it

> For the PATCH, maybe you need to change the header: https://www.hl7.org/fhir/http.html#patch?

Thanks ! I'll look into it and add a commit if this works

**Comment by MiskoG** [comment]
Haha @BPierrick great don't worry about the loading state screenshot. Looks great !

**Comment by BPierrick** [comment]
@Jasopaum I've added `content-type: application/json-patch+json` in my header request as requested. I still get an error 400 for patches

URL : `https://demo.arkhn.com/hapi/fhir/Group/9658?_format=[mime-type]`

Request body is like this :

Capture d’écran 2021-04-07 à 12 13 30

**Review by Jasopaum — APPROVED** [review]
A PUT will be ok 👍

**Comment by simonvadee** [comment]
setting the header `content-type: application/json-patch+json` is not enough, the body must effectively be a JSONPatch (which follows a strict format, it's not plain json). We'll deal with that later, a PUT is fine I agree :+1:

**Pull request merged**
